### ISSUE TITLE
Can this work as a PWA?

### ISSUE THREAD

**Issue by jundalisay** [jetthoughts/vuejs-rails-5-starterkit#15]
I just started learning PWAs. Can this work with a Vue-based service worker `vue init pwa` or a Rails-based serviceworker `gem "serviceworker-rails"` ?

**Comment by pftg** [comment]
Idea was to use Turbolinks in order to have similar features like PWA.

**Comment by pftg** [comment]
@jundalisay will add PWA example on the next week

**Comment by pftg** [comment]
@jundalisay there are 2 solutions:

1. Use `serviceworker-rails` like gems
2. Add own code to allow process `sw` files in a recommended way to provide those files like `serviceworker-rails`: no caching, no digest, specific headers for nested paths

Added example how to do it on https://github.com/jetthoughts/vuejs-rails-5-starterkit/tree/service-worker you could check.

**Comment by jundalisay** [comment]
Thanks! I'll try it next month. I'm trying out Vue with Google Workbox and Rails API

**Comment by pftg** [comment]
I'll add example how to use workbox - it's much simpler, would like to remove `serviceworker-rails` and use workbox + webpack plugin as example
