### ISSUE TITLE
Setup CSP

### ISSUE THREAD

**Issue by ledermann** [jetthoughts/vuejs-rails-5-starterkit#17]
I'm building a Rails app with Vuetify, too - and have trouble setting up CSP (content security policy) with Vuetify theming. I would like to see how you are doing this.

In the Vuetify docs using a nonce for CSP is recommended:
https://vuetifyjs.com/en/style/theme#introduction

I have tried it without success, the generated theme always has an empty nonce. Here is my code:

**config/initializers/content_security_policy.rb:**
```ruby
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval
    policy.connect_src :self, :https, 'http://localhost:3035', 'ws://localhost:3035'
  else
    policy.default_src :self, :https
    policy.font_src    :self, :https, :data
    policy.img_src     :self, :https, :data
    policy.object_src  :none
    policy.script_src  :self, :https
    policy.style_src   :self, :https
  end

  # Specify URI for violation reports
  # policy.report_uri "/csp-violation-report-endpoint"
end

# If you are using UJS then enable automatic nonce generation
Rails.application.config.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
```

**app/javascript/packs/application.js:**
```javascript
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

const railsNonce = document.querySelector('meta[name=csp-nonce]').getAttribute('content')

Vue.use(Vuetify, {
  options: {
    cspNonce: railsNonce,
  },
})
```

**Comment by ledermann** [comment]
Oops, wrong repo - you didn't use Vuetify here :-)
Nevertheless, adding CSP would be a good thing.

**Comment by pftg** [comment]
@ledermann have you reviewed https://bauland42.com/ruby-on-rails-content-security-policy-csp/ ?
